### ISSUE TITLE
segfault in SizeMe.xs:1929

### ISSUE THREAD

**Issue by sni** [timbunce/devel-sizeme#13]
When trying todays HEAD (710ef78e7), i got a sigsegv while running perl_size()

```
[Thread debugging using libthread_db enabled]
[New Thread 0xb791eb70 (LWP 20620)]
[New Thread 0xb6fffb70 (LWP 20621)]
[New Thread 0xb67feb70 (LWP 20622)]
[New Thread 0xb5ffdb70 (LWP 20623)]
[New Thread 0xb57fcb70 (LWP 20624)]
[New Thread 0xb49ffb70 (LWP 20625)]
[New Thread 0xb38ffb70 (LWP 20631)]
Calculated sizes for compiled regexes are incomplete
Devel::Size: Unknown variable type: 208 encountered
SV = UNKNOWN(0xd0) (0x0) at 0x837bc80
  REFCNT = 0
  FLAGS = (PADSTALE,PADMY,TEMP,IOK,NOK,READONLY,pIOK,pPOK)
Devel::Size: Calculated sizes for FMs are incomplete
Devel::Size: Unknown variable type: 192 encountered
SV = UNKNOWN(0xc0) (0x8397ed8) at 0x81955d8
  REFCNT = 137985752
  FLAGS = (PADSTALE,PADMY,TEMP,NOK,READONLY,pIOK,pPOK)

Program received signal SIGSEGV, Segmentation fault.
0xb7c8d352 in deferred_by_refcnt_size (my_perl=0x8177008, st=0xcc89ad0, NPathArg=0xbffff318, cycle=1) at SizeMe.xs:1929
warning: Source file is more recent than executable.
1929                if (visitcnt < SvREFCNT(sv)) {
(gdb) bt
#0  0xb7c8d352 in deferred_by_refcnt_size (my_perl=0x8177008, st=0xcc89ad0, NPathArg=0xbffff318, cycle=1) at SizeMe.xs:1929
#1  0xb7c8efb1 in perl_size (my_perl=0x8177008, st=0xcc89ad0, NPathArg=0x0) at SizeMe.xs:2211
#2  0xb7c8f3eb in XS_Devel__SizeMe_perl_size (my_perl=0x8177008, cv=0x81d06b8) at SizeMe.xs:2287
#3  0x080d5af3 in Perl_pp_entersub ()
#4  0x080d3ee8 in Perl_runops_standard ()
#5  0x0807c7c5 in perl_run ()
#6  0x0806437d in main ()
(gdb)
```

**Comment by timbunce** [comment]
I've merged the refcnt branch into the sizeme branch in preparation for release. Please retry with the sizeme branch. Thanks.
